config/routes.rb
Rails.application.routes.draw do

	resources :operations, only: [:show]
	
	post "/carrier_info", to: "operations#carrier_info"
	put "/change_difficulty", to: "operations#change_difficulty", as: "change_difficulty"

	namespace :documents do
		get "/booking_sheet/:operation_id", to: "booking_sheet#show", as: "booking_sheet"
		get "/slis/:operation_id", to: "sli#show", as: "sli"
		get "/slis/new/:secure_id", to: "sli#new", as: "new_sli"
		post "/slis/create/:secure_id", to: "sli#create", as: "create_sli"
		post "/slis/request_sli/:secure_id", to: "sli#request_sli", as: "request_sli"
		post "/slis/tariff_group", to: "sli#tariff_group", as: "tariff_group"
		get "/invoices/new/:secure_id", to: "invoice#new", as: "new_invoice"
		post "/invoices/create/:secure_id", to: "invoice#create", as: "create_invoice"
		post "/invoices/request_invoice/:secure_id", to: "invoice#request_invoice", as: "request_invoice"
		post "/documents_transfer/:operation_id", to: "documents_transfer#send_mail", as: 'send_documents'
		get 'insurance/new/:secure_id', to: 'insurance#new', as: 'insurance_form'
		get 'insurance/view_pdf/:secure_id', to: 'insurance#view_pdf', as: 'insurance_pdf'
		post 'insurance/create', to: 'insurance#create', as: 'insurance_create'
		post 'insurance/send_info/:operation_id', to: 'insurance#send_info', as: 'insurance_send_info'
		post "/quotation_sell_prices", to: 'quotation_selling#confirm'
		get "/quotation_sell/:id", to: "quotation_selling#show", as: "quotation_sell"
	end

	namespace :fcl_exw_steps do 
		post "/confirm_loading", to: "container_loadings#confirm_loading", as: "confirm_loading"
		post "/confirm_delivery", to: "container_deliveries#confirm_delivery", as: "confirm_delivery"
		post "/request_booking", to: "request_bookings#request_booking"
		resources :cargo_info, only: [:new, :create]
		resources :booking_info, only: [:new, :create]
	end

	namespace :lcl_steps do
		resources :cargo_info, only: [:new, :create]
		post "/request_booking", to: "request_bookings#request_booking"
	end

	namespace :common_steps do
		post "/confirm_info", to: "info_confirmed#confirm_info"
		post "/info", to: "info_requested#request_info"
		post "/quotation/new/:secure_id", to: "quotation_confirmed#update_pricing", as: "new_quotation"
		get  "/quotation/new/:secure_id", to: "quotation_confirmed#new", as: "new_quotation_view"
		post "/confirm_quotation", to: "quotation_confirmed#confirm_quotation"
		post "/pieces", to: "pieces#pieces_for_cargo_info", as: "pieces"
	end

	namespace :charts do
		match "/admin/general_charts", to: "generals#index", as: "general", via: [:get, :post]
		match "/admin/customers_charts", to: "customers#index", as: "customers", via: [:get, :post]
		match "/admin/representatives_charts", to: "representatives#index", as: "representatives", via: [:get, :post]
	end

	namespace :records_lists do
		match "/admin/general_records", to: "generals#index", as: "general", via: [:get, :post]
		match "/admin/customers_records", to: "customers#index", as: "customers", via: [:get, :post]
		match "/admin/representatives_records", to: "representatives#index", as: "representatives", via: [:get, :post]
	end

	namespace :generals do	
		get "/tasks/:id", to: "tasks#show", as: "task"
		post "/tasks", to: "tasks#create", as: "tasks"
		put "/update_tasks", to: "tasks#update", as: "update_tasks"
	end

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		registrations: 'users/registrations'
	}
	namespace :users do	
		match "/representative", to: "representatives#index", as: "representative", via: [:get, :post]
		get '/admin', to: "admins#index", as: "admin"
		get 'relationship/new/:representative_id', to: 'relationships#new', as: 'new_relationship'
		post 'relationship/create', to: 'relationships#create' ,as: 'create_relationship'
		delete 'relationship/destroy', to: 'relationships#destroy' , as: 'destroy_relationship'
		get 'relationship/index_representatives', to: 'relationships#index_representatives', as: 'representatives_list'
		match "/team_leader", to: "teams#index", as: "team", via: [:get, :post]
		get "/team_leader/:id", to: "teams#show", as: "team_member"
		post "/team_leader/change_representative", to: "teams#change_representative", as: "change_representative"
	end
  get '/users/edit/:id', to: 'users#edit', as: 'user'
  patch '/users/edit/:id', to: 'users#update'

  namespace :operations do
  	resources :operations_by_users, only: [:new, :create, :edit, :update]
  end


  devise_scope :user do
	  authenticated :user do
	    root to: 'roots_selector#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end
end

app/models/fcl_exw_steps/booking_info.rb
module FclExwSteps
  class BookingInfo < ApplicationRecord
    self.table_name = 'fcl_exw_steps_booking_infos'

  	strip_attributes
  	belongs_to :operation
  	has_many :tasks, dependent: :destroy

  	def self.create_pieces (params, cargo_info)
    	CommonSteps::Piece.where(fcl_exw_steps_cargo_info_id: cargo_info.id).delete_all
    	params_array = params.to_unsafe_h.to_a.drop(3)[0..-4]
      (0..params_array.length).step(9) do |element|
      	unless params_array[element].nil?
        	piece = CommonSteps::Piece.create!(fcl_exw_steps_cargo_info_id: cargo_info.id, gross_weight: params_array[element][1], commercial_description: params_array[element+1][1], container_size: params_array[element+2][1], cargo_hazardous: params_array[element+3][1], hazardous_class: params_array[element+4][1], un_code: params_array[element+5][1], container_number: params_array[element+6][1], seal_number: params_array[element+7][1], tare_weight: params_array[element+8][1] )
      	end
      end
    end

    def self.create_tasks(params)
    	existing_booking_info = existing_fcl_booking_info(Operation.find_by(secure_id: params[:operation_secure_id]).id)
      create_doc_cut_off_tasks(params, existing_booking_info)
      create_cargo_cut_off_tasks(params, existing_booking_info)
      create_vgm_cut_off_tasks(params, existing_booking_info)
      create_sailing_date_tasks(params, existing_booking_info)
      create_arrival_date_tasks(params, existing_booking_info)
      create_ramp_cut_off_tasks(params, existing_booking_info)
    end

    def self.save_record(fcl_booking_info_params, operation, current_user)
    	existing_booking_info = existing_fcl_booking_info(operation.id)
  	   
      if existing_booking_info.created_at == existing_booking_info.updated_at
  			operation.update!(fcl_exw_quotation_confirmed: true, status: 'IN PROGRESS', current_step: operation.current_step + 1, status_message: 'Confirm Container Loading')
      end
        
      if existing_booking_info.update!(fcl_booking_info_params.merge(operation_id: operation.id))
        agent = Operations::OperationsByUser.find_by(operation_id: operation.id).agent
  			FclExwOperationMailer.booking_info(agent, current_user, existing_booking_info).deliver_later
        #FclExwOperationMailer.transfer_documents("", operation, current_user).deliver_later
  			true
  		else
  			false
  		end
    end

  	def self.existing_fcl_booking_info (operation_id)
  	  FclExwSteps::BookingInfo.find_by(operation_id: operation_id)
  	end

    private
      def self.create_doc_cut_off_tasks(params, existing_booking_info)
        if (params[:fcl_exw_steps_booking_info][:doc_cut_off_date].present?)
          if existing_booking_info.doc_cut_off_date.nil?
            Generals::Task.create!(note: 'Document cut off date set.' , due_date: params[:fcl_exw_steps_booking_info][:doc_cut_off_date], fcl_exw_steps_booking_info_id: existing_booking_info.id, operation_id: Operation.find_by(secure_id: params[:operation_secure_id]).id, subject: 'Documments Cut Off Date' )
          else
            Generals::Task.where(subject: 'Documments Cut Off Date', fcl_exw_steps_booking_info_id: existing_booking_info.id).first.update!(due_date: params[:fcl_exw_steps_booking_info][:doc_cut_off_date], status: '0')
          end
        end
      end

      def self.create_cargo_cut_off_tasks(params, existing_booking_info)
        if (params[:fcl_exw_steps_booking_info][:cargo_cut_off_date].present?)
          if existing_booking_info.cargo_cut_off_date.nil?
            Generals::Task.create!(note: 'Cargo cut off date set.', due_date: params[:fcl_exw_steps_booking_info][:cargo_cut_off_date], fcl_exw_steps_booking_info_id: existing_booking_info.id, operation_id: Operation.find_by(secure_id: params[:operation_secure_id]).id, subject: 'Cargo Cut Off Date' )
          else
            Generals::Task.where(subject: 'Cargo Cut Off Date', fcl_exw_steps_booking_info_id: existing_booking_info.id).first.update!(due_date: params[:fcl_exw_steps_booking_info][:cargo_cut_off_date], status: '0')
          end
        end
      end

      def self.create_vgm_cut_off_tasks(params, existing_booking_info)
        if (params[:fcl_exw_steps_booking_info][:vgm_cut_off_date].present?)
          if existing_booking_info.vgm_cut_off_date.nil?
            Generals::Task.create!(note: 'VGM cut off date set.', due_date: params[:fcl_exw_steps_booking_info][:vgm_cut_off_date], fcl_exw_steps_booking_info_id: existing_booking_info.id, operation_id: Operation.find_by(secure_id: params[:operation_secure_id]).id, subject: 'VGM Cut Off Date' )
          else
            Generals::Task.where(subject: 'VGM Cut Off Date', fcl_exw_steps_booking_info_id: existing_booking_info.id).first.update!(due_date: params[:fcl_exw_steps_booking_info][:vgm_cut_off_date], status: '0')
          end
        end
      end

      def self.create_sailing_date_tasks(params, existing_booking_info)
        if (params[:fcl_exw_steps_booking_info][:sailing_date].present?)
          if existing_booking_info.sailing_date.nil?
            Generals::Task.create!(note: 'Expected sailing date set.', due_date: params[:fcl_exw_steps_booking_info][:sailing_date], fcl_exw_steps_booking_info_id: existing_booking_info.id, operation_id: Operation.find_by(secure_id: params[:operation_secure_id]).id, subject: 'Sailing Date' )
            Generals::Task.create!(note: 'Check if cargo is on port and ready to sail', due_date: (params[:fcl_exw_steps_booking_info][:arrival_date]).to_date - 3.days, fcl_exw_steps_booking_info_id: existing_booking_info.id, operation_id: Operation.find_by(secure_id: params[:operation_secure_id]).id, subject: 'Cargo On Port' )
          else
            Generals::Task.where(subject: 'Sailing Date', fcl_exw_steps_booking_info_id: existing_booking_info.id).first.update!(due_date: params[:fcl_exw_steps_booking_info][:sailing_date], status: '0')
            Generals::Task.where(subject: 'Cargo On Port', fcl_exw_steps_booking_info_id: existing_booking_info.id).first.update!(due_date: (params[:fcl_exw_steps_booking_info][:sailing_date]).to_date - 3.days, status: '0')
          end
        end
      end

      def self.create_arrival_date_tasks(params, existing_booking_info)
        if (params[:fcl_exw_steps_booking_info][:arrival_date].present?)
          if existing_booking_info.arrival_date.nil?
            Generals::Task.create!(note: 'Expected arrival date set.', due_date: params[:fcl_exw_steps_booking_info][:arrival_date], fcl_exw_steps_booking_info_id: existing_booking_info.id, operation_id: Operation.find_by(secure_id: params[:operation_secure_id]).id, subject: 'Arrival Date' )
          else
            Generals::Task.where(subject: 'Arrival Date', fcl_exw_steps_booking_info_id: existing_booking_info.id).first.update!(due_date: params[:fcl_exw_steps_booking_info][:arrival_date], status: '0')
          end
        end
      end

      def self.create_ramp_cut_off_tasks(params, existing_booking_info)
        existing_task = Generals::Task.where(subject: 'Ramp Cut Off Date', fcl_exw_steps_booking_info_id: existing_booking_info.id).first
        if (params[:fcl_exw_steps_booking_info][:ramp] == "YES")
          if existing_task.nil? && !(params[:fcl_exw_steps_booking_info][:ramp_cut_off_date]).nil?
            Generals::Task.create!(note: 'Verify that container was included in ramp transportation.', due_date: (params[:fcl_exw_steps_booking_info][:ramp_cut_off_date]).to_date + 1.day , fcl_exw_steps_booking_info_id: existing_booking_info.id, operation_id: Operation.find_by(secure_id: params[:operation_secure_id]).id, subject: 'Ramp Cut Off Date' )
          elsif !(params[:fcl_exw_steps_booking_info][:ramp_cut_off_date]).nil?
            existing_task.update!(due_date: params[:fcl_exw_steps_booking_info][:ramp_cut_off_date], status: '0')
          end
        elsif (params[:fcl_exw_steps_booking_info][:ramp] == "NO")
          unless existing_task.nil?
            existing_task.delete
          end
        end
      end
  end
end

app/models/fcl_exw_steps/container_delivery.rb
module FclExwSteps  	
	class ContainerDelivery < ApplicationRecord
		self.table_name = 'fcl_exw_steps_container_deliveries'
		has_many :tasks
		belongs_to :operation


		def self.confirm_delivery(params, current_user)
			shipper = User.find(params[:shipper_id])
			agent = User.find(params[:agent_id])
			op = Operation.find(params[:operation_id])
			step = FclExwSteps::ContainerDelivery.find_by(operation_id: params[:operation_id])
			if step.created_at == step.updated_at
				op.update(status: 'COMPLETED' ,status_message: 'Completed', current_step: op.current_step + 1)
			end

			step.update(completed: true)
			FclExwOperationMailer.container_delivery(agent, op, shipper, current_user).deliver_later
			true
		end
	end
end

app/models/fcl_exw_steps/container_loading.rb
module FclExwSteps  	
	class ContainerLoading < ApplicationRecord
		has_many :tasks
		belongs_to :operation
		self.table_name = 'fcl_exw_steps_container_loadings'

		def self.confirm_loading(params, current_user)
			shipper = User.find(params[:shipper_id])
			agent = User.find(params[:agent_id])
			op = Operation.find(params[:operation_id])
			step = FclExwSteps::ContainerLoading.find_by(operation_id: params[:operation_id])
			if step.created_at == step.updated_at
				op.update(status: 'IN PROGRESS' ,status_message: 'Confirm Container Delivery', current_step: op.current_step + 1)
			end

			step.update(completed: true)
			FclExwOperationMailer.container_loading(agent, op, shipper, current_user).deliver_later
			true
		end
	end
end

app/models/fcl_exw_steps/fcl_exw_container_delivery.rb
module FclExwSteps  	
	class FclExwContainerDelivery < ApplicationRecord
		has_many :tasks
		belongs_to :operation


		def self.confirm_delivery(params, current_user)
			shipper = User.find(params[:shipper_id])
			agent = User.find(params[:agent_id])
			op = Operation.find(params[:operation_id])
			step = FclExwSteps::FclExwContainerDelivery.find_by(operation_id: params[:operation_id])
			if step.created_at == step.updated_at
				op.update(status: 'COMPLETED' ,status_message: 'Completed', current_step: op.current_step + 1)
			end

			step.update(completed: true)
			FclExwOperationMailer.container_delivery(agent, op, shipper, current_user).deliver_later
			true
		end
	end
end

app/models/fcl_exw_steps/fcl_exw_quotation_selling_step.rb
module FclExwSteps  	
	class FclExwQuotationSellingStep < ApplicationRecord
		mount_uploaders :files, FileUploader
		
		def filename
		  File.basename(path)
		end
	end
end

app/controllers/fcl_exw_steps/booking_info_controller.rb
module FclExwSteps
	class BookingInfoController < ApplicationController
	  def new
	  	@fcl_booking_info = FclExwSteps::BookingInfo.new
	  	@operation = Operation.find_by(secure_id: params[:operation_secure_id])
	  end

	  def create
			operation = Operation.find_by(secure_id: params[:operation_secure_id])
			cargo_info = FclExwSteps::CargoInfo.find_by(operation_id: operation.id)
			FclExwSteps::BookingInfo.create_pieces(params, cargo_info)
			FclExwSteps::BookingInfo.create_tasks(params)

			if FclExwSteps::BookingInfo.save_record(fcl_booking_info_params, operation, current_user)
				flash[:notice] = 'Information correctly updated'
				redirect_to operation_path operation.id
			else
				flash[:alert] = 'Information could not be saved, please fill in all the information listed bellow'
				redirect_to new_fcl_exw_steps_cargo_info_path(operation_id: operation.id)
			end
	  end

		private	
			def fcl_booking_info_params
				params.require(:fcl_exw_steps_booking_info).permit(:operation_id, :vgm_cut_off_date, :booking_number, :vessel, :voyage, :doc_cut_off_date, :doc_cut_off_time, 
					:cargo_cut_off_date, :cargo_cut_off_time, :sailing_date, :arrival_date, :ramp, :ramp_cut_off_date)
			end
	end
end

app/controllers/fcl_exw_steps/cargo_info_controller.rb
module FclExwSteps	
	class CargoInfoController < ApplicationController
		def new
			@fcl_cargo_info = FclExwSteps::CargoInfo.new
			@operation = Operation.find_by(secure_id: params[:operation_secure_id])
		end

		def create
			@fcl_cargo_info = FclExwSteps::CargoInfo.new
			op = Operation.find_by(secure_id: params[:operation_secure_id])
		  if FclExwSteps::CargoInfo.create_cargo_info(params, fcl_cargo_info_params)
		  	flash[:notice] = 'Information correctly updated'
		  	if current_user
		  		redirect_to operation_path op.id
		  	else
		  		redirect_back(fallback_location: unauthenticated_root_path)
		  	end
		  else
		  	flash[:alert] = 'Information could not be saved, please fill in all the information listed bellow'
		  	if current_user
		  		redirect_to new_fcl_exw_steps_cargo_info_step_path(operation_id: op.id)
		  	else
		  		redirect_back(fallback_location: unauthenticated_root_path)
		  	end
		  end
		end

		private
			def fcl_cargo_info_params
				params.require(:fcl_exw_steps_cargo_info).permit({files: []}, :operation_id, :loading_address, :loading_date, :loading_time, :gross_weight, :commercial_description, :cargo_hazardous, :hazardous_document, :pickup_reference, :contact_name, :contact_email, :contact_number, :contact_company, :pieces_number, :bonded, :self_propelled)
			end
	end
end

app/views/fcl_exw_steps/cargo_info/new.html.erb
<div class="container is-widescreen"> 
  <div class="columns">
    <div class="column is-10 is-offset-1" >
      <br>
      <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
          <li><%= link_to "Operation Timeline", operation_path(@operation) %></li>
          <li class="is-active"><a href="">Cargo Information </a></li>
        </ul>
      </nav>

      <div class="notification is-primary">
        All the information requested in this form is <strong>mandatory</strong>, but you don't have to provide all the info at once (the form is updatable).
      </div>

      <nav class= 'panel is-form-panel card-shadow' >
        <p class="panel-heading">
          FCL - EXW Cargo information for operation: <%= @operation.reference %>
        </p>
        <div class='panel-block'>
          <%= form_for @fcl_cargo_info, url: fcl_exw_steps_cargo_info_index_path, id: '', html: {class: "control"}, multipart: true, remote: true do |f| %>
            <%= render 'shared/error_messages', format: params[:format] %>
            <%= hidden_field_tag :operation_secure_id, params[:operation_secure_id] %>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Loading Address:</label>
                  <div class="control has-icons-left">
                    <%= f.text_field :loading_address, class: 'input with-guide', value: is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).loading_address : '' %>
                    <div class="icon is-small is-left">
                      <i class="fas fa-globe"></i>
                    </div>
                  </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal loading-address">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Contact Email:</label>
                  <div class="control has-icons-left">
                    <%= f.text_field :contact_email, class: 'input with-guide', value: is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).contact_email : '' %>
                    <div class="icon is-small is-left">
                      <i class="fas fa-user"></i>
                    </div>
                  </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal contact-email">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Contact Phone:</label>
                  <div class="control has-icons-left">
                    <%= f.text_field :contact_number, class: 'input with-guide', value: is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).contact_number : '' %>
                    <div class="icon is-small is-left">
                      <i class="fas fa-user"></i>
                    </div>
                  </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal contact-phone">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Loading Date:</label>
                  <div class="control has-icons-left">
                    <%= f.text_field :loading_date, class: 'input loading_datetime with-guide', value: is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).loading_date : '' %>
                    <div class="icon is-small is-left">
                      <i class="fas fa-calendar-alt"></i>
                    </div>
                  </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal loading-date">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Loading Time:</label>
                  <div class="control has-icons-left">
                    <%= f.time_select :loading_time, { default: default_time(existing_fcl_cargo_info(@operation).loading_time) }, { class: 'input time-input' } %>
                    <span class="icon is-small is-left">
                      <i class="fas fa-clock"></i>
                    </span>
                  </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal loading-time">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <% unless existing_fcl_cargo_info(@operation).loading_time.nil? %>
              <p class="hour hidden"><%= hour(@operation) %></p>
              <p class="mins hidden"><%= minute(@operation) %></p>
            <% end %>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Pick Up Reference:</label>
                    <div class="control has-icons-left">
                      <%= f.text_field :pickup_reference, class: 'input with-guide', value: is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).pickup_reference : '' %>
                      <span class="icon is-small is-left">
                        <i class="fas fa-file-alt"></i>
                      </span>
                    </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal pick-up-reference">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* EIN:</label>
                    <div class="control has-icons-left">
                      <%= f.text_field :ein, class: 'input with-guide', value: ein(@operation).nil? ? '' : ein(@operation) %>
                      <span class="icon is-small is-left">
                        <i class="fas fa-file-alt"></i>
                      </span>
                    </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal ein">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Bonded:</label>
                  <div class="control has-icons-left">
                    <div class="select">
                      <%= f.select :bonded, options_for_select([['NO', false], ['YES', true]], is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).bonded : '' ), {}, class: 'input'  %>
                    </div>
                    <span class="icon is-small is-left">
                      <i class="fas fa-cubes"></i>
                    </span>
                  </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal bonded">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Self Propelled:</label>
                  <div class="control has-icons-left">
                    <div class="select">
                      <%= f.select :self_propelled, options_for_select([['NO', false], ['YES', true]], is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).self_propelled : '' ), {}, class: 'input'  %>
                    </div>
                    <span class="icon is-small is-left">
                      <i class="fas fa-car"></i>
                    </span>
                  </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal self-propelled">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <label class="label">* Number of Containers:</label>
                  <div class="control has-icons-left">
                    <%= f.number_field :pieces_number, class: 'input pieces-number-diff', min: 0, value: is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).pieces_number : '' %>
                    <span class="icon is-small is-left">
                      <i class="fas fa-envelope pieces-number-diff"></i>
                    </span>
                  </div>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal containers-number">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>

            <%= f.hidden_field :fcl_exw_steps_cargo_info_id, class: "fcl_exw_steps_cargo_info_id", value: is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? existing_fcl_cargo_info(@operation).id : '' %>
            <br>
            <div id="container"></div>

            <div class="columns">
              <div class="column is-11">
                <div class="field">
                  <%= f.label 'Upload documents related to the cargo HAZMAT, SELF PROPELLED, BONDED, ETC...', class: 'label' %>                  
                  <%= f.file_field :files, multiple: true %>
                </div>
              </div>
              <div class="column is-1">
                <br>
                <a class="show-modal documents">
                  <i class="fas fa-info-circle guide-btn"></i>
                </a>
              </div>
            </div>
            <ul>
              <% existing_fcl_cargo_info(@operation).files.each do |file| %>
                <li> <%= link_to file.path.split("/").last, file.url, target: 'blank' %>  </li>
              <% end %>
            </ul>
            <br>

            <div class="control">
              <br>
              <%= f.submit is_fcl_exw_info_stage_completed?(params[:operation_secure_id]) ? "UPDATE CARGO INFO" : "REGISTER CARGO INFO" , class: 'button is-link' %>
            </div>
            <br>
          <% end %>
        </div>
      </nav>
    </div>
  </div>
</div>
<%= render 'guides/cargo_info/main_guide' %>