config/routes.rb
Rails.application.routes.draw do

	resources :operations, only: [:show]
	
	post "/carrier_info", to: "operations#carrier_info"
	put "/change_difficulty", to: "operations#change_difficulty", as: "change_difficulty"

	namespace :documents do
		get "/booking_sheet/:operation_id", to: "booking_sheet#show", as: "booking_sheet"
		get "/slis/:operation_id", to: "sli#show", as: "sli"
		get "/slis/new/:secure_id", to: "sli#new", as: "new_sli"
		post "/slis/create/:secure_id", to: "sli#create", as: "create_sli"
		post "/slis/request_sli/:secure_id", to: "sli#request_sli", as: "request_sli"
		post "/slis/tariff_group", to: "sli#tariff_group", as: "tariff_group"
		get "/invoices/new/:secure_id", to: "invoice#new", as: "new_invoice"
		post "/invoices/create/:secure_id", to: "invoice#create", as: "create_invoice"
		post "/invoices/request_invoice/:secure_id", to: "invoice#request_invoice", as: "request_invoice"
		post "/documents_transfer/:operation_id", to: "documents_transfer#send_mail", as: 'send_documents'
		get 'insurance/new/:secure_id', to: 'insurance#new', as: 'insurance_form'
		get 'insurance/view_pdf/:secure_id', to: 'insurance#view_pdf', as: 'insurance_pdf'
		post 'insurance/create', to: 'insurance#create', as: 'insurance_create'
		post 'insurance/send_info/:operation_id', to: 'insurance#send_info', as: 'insurance_send_info'
		post "/quotation_sell_prices", to: 'quotation_selling#confirm'
		get "/quotation_sell/:id", to: "quotation_selling#show", as: "quotation_sell"
	end

	namespace :fcl_exw_steps do 
		post "/confirm_loading", to: "container_loadings#confirm_loading", as: "confirm_loading"
		post "/confirm_delivery", to: "container_deliveries#confirm_delivery", as: "confirm_delivery"
		post "/request_booking", to: "request_bookings#request_booking"
		resources :cargo_info, only: [:new, :create]
		resources :booking_info, only: [:new, :create]
	end

	namespace :lcl_steps do
		resources :cargo_info, only: [:new, :create]
		post "/request_booking", to: "request_bookings#request_booking"
	end

	namespace :common_steps do
		post "/confirm_info", to: "info_confirmed#confirm_info"
		post "/info", to: "info_requested#request_info"
		post "/quotation/new/:secure_id", to: "quotation_confirmed#update_pricing", as: "new_quotation"
		get  "/quotation/new/:secure_id", to: "quotation_confirmed#new", as: "new_quotation_view"
		post "/confirm_quotation", to: "quotation_confirmed#confirm_quotation"
		post "/pieces", to: "pieces#pieces_for_cargo_info", as: "pieces"
	end

	namespace :charts do
		match "/admin/general_charts", to: "generals#index", as: "general", via: [:get, :post]
		match "/admin/customers_charts", to: "customers#index", as: "customers", via: [:get, :post]
		match "/admin/representatives_charts", to: "representatives#index", as: "representatives", via: [:get, :post]
	end

	namespace :records_lists do
		match "/admin/general_records", to: "generals#index", as: "general", via: [:get, :post]
		match "/admin/customers_records", to: "customers#index", as: "customers", via: [:get, :post]
		match "/admin/representatives_records", to: "representatives#index", as: "representatives", via: [:get, :post]
	end

	namespace :generals do	
		get "/tasks/:id", to: "tasks#show", as: "task"
		post "/tasks", to: "tasks#create", as: "tasks"
		put "/update_tasks", to: "tasks#update", as: "update_tasks"
	end

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		registrations: 'users/registrations'
	}
	namespace :users do	
		match "/representative", to: "representatives#index", as: "representative", via: [:get, :post]
		get '/admin', to: "admins#index", as: "admin"
		get 'relationship/new/:representative_id', to: 'relationships#new', as: 'new_relationship'
		post 'relationship/create', to: 'relationships#create' ,as: 'create_relationship'
		delete 'relationship/destroy', to: 'relationships#destroy' , as: 'destroy_relationship'
		get 'relationship/index_representatives', to: 'relationships#index_representatives', as: 'representatives_list'
		match "/team_leader", to: "teams#index", as: "team", via: [:get, :post]
		get "/team_leader/:id", to: "teams#show", as: "team_member"
		post "/team_leader/change_representative", to: "teams#change_representative", as: "change_representative"
	end
  get '/users/edit/:id', to: 'users#edit', as: 'user'
  patch '/users/edit/:id', to: 'users#update'

  namespace :operations do
  	resources :operations_by_users, only: [:new, :create, :edit, :update]
  end


  devise_scope :user do
	  authenticated :user do
	    root to: 'roots_selector#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end
end

app/models/charts/general.rb
module Charts 
  class General
    include OperationQueriable
    include ChartTimeOrganizable

    def self.fetch_general_charts(date_range, modality)

    	all_operations = query_general_charts_operations(set_general_operations, modality)
    	comleted_operations = query_general_charts_operations(set_general_operations.where('operations.status =?', 'COMPLETED'), modality)
    	in_progress_operations = query_general_charts_operations(set_general_operations.where.not('operations.status =?', 'COMPLETED'), modality)

    	charts_info = [
    		set_charts_date_range(all_operations, date_range), 
    		set_charts_date_range(comleted_operations, date_range), 
    		set_charts_date_range(in_progress_operations, date_range) 
    	]
    end

    private
    	def self.query_general_charts_operations(operations, modality)
    		if modality == "ALL"
    			operations
    		else
    			query_by_modality(operations, modality)
    		end
    	end
  end
end

app/models/generals/task.rb
module Generals  
  class Task < ApplicationRecord
    belongs_to :fcl_exw_steps_cargo_info, optional: true
    belongs_to :fcl_exw_steps_booking_info, optional: true
    belongs_to :common_steps_info_confirmed, optional: true
    belongs_to :common_steps_info_requested, optional: true
    belongs_to :fcl_exw_steps_quotation_confirmed, optional: true

    belongs_to :fcl_exw_steps_container_delivery, optional: true

    belongs_to :fcl_exw_steps_container_loading, optional: true

    belongs_to :operation


    validates :note, :due_date, presence: true

    def self.get_data(current_user, due_date)
    	if due_date == 'today'
    		Generals::Task.where(operation_id: Operations::OperationsByUser.where(representative_id: current_user))
    			.where(status: 0)
    			.where(due_date: Date.today)
    	elsif due_date == 'this_week'
    		Generals::Task.where(operation_id: Operations::OperationsByUser.where(representative_id: current_user))
    			.where(status: 0)
    			.where('due_date < ?', Date.today + 7.days)
    	elsif due_date == 'this_month'
    		Generals::Task.where(operation_id: Operations::OperationsByUser.where(representative_id: current_user))
    			.where(status: 0)
    			.where('due_date < ?', Date.today + 30.days)
      elsif due_date == 'all'
        Generals::Task.where(operation_id: Operations::OperationsByUser.where(representative_id: current_user))
          .where(status: 0)
    	end
   	end

    def self.new_task(params)
      if params[:fcl_exw_cargo_info_step]
        Generals::Task.new(note: params[:note], due_date: params[:due_date], fcl_exw_steps_cargo_info_id: params[:fcl_exw_cargo_info_step], operation_id: params[:operation_id] )
      elsif params[:fcl_exw_info_confirmed_step]
        Generals::Task.new(note: params[:note], due_date: params[:due_date], common_steps_info_confirmed_id: params[:fcl_exw_info_confirmed_step], operation_id: params[:operation_id] )
      elsif params[:fcl_exw_info_requested_step]
        Generals::Task.new(note: params[:note], due_date: params[:due_date], common_steps_info_requested_id: params[:fcl_exw_info_requested_step], operation_id: params[:operation_id] )
      elsif params[:fcl_exw_quotation_confirmed_step]
        Generals::Task.new(note: params[:note], due_date: params[:due_date], common_steps_quotation_confirmed_id: params[:fcl_exw_quotation_confirmed_step], operation_id: params[:operation_id] )
      elsif params[:fcl_exw_request_booking_step]
        Generals::Task.new(note: params[:note], due_date: params[:due_date], fcl_exw_steps_request_bookings_id: params[:fcl_exw_request_booking_step], operation_id: params[:operation_id] )
      elsif params[:fcl_exw_booking_info_steps]
        Generals::Task.new(note: params[:note], due_date: params[:due_date], fcl_exw_steps_booking_info_id: params[:fcl_exw_booking_info_steps], operation_id: params[:operation_id] )
      elsif params[:fcl_exw_container_delivery_step]
        Generals::Task.new(note: params[:note], due_date: params[:due_date], fcl_exw_steps_container_delivery_id: params[:fcl_exw_container_delivery_step], operation_id: params[:operation_id] )
      elsif params[:fcl_exw_container_loading_step]
        Generals::Task.new(note: params[:note], due_date: params[:due_date], fcl_exw_steps_container_loading_id: params[:fcl_exw_container_loading_step], operation_id: params[:operation_id] )
      end
    end
  end
end

app/models/records_lists/general.rb
module RecordsLists  
  class General
    include OperationQueriable
    include OperationSortable
    
    # query_params is an array where elements are:
      # 1) modality
      # 2) status
      # 3) search
    def self.fetch_general_operations(sort_param, query_params)
      query_params[0] = query_params[0] == 'ALL' ? nil : query_params[0]
      query_params[1] = query_params[1] == 'ALL' ? nil : query_params[1]

      operations = query_general_operations(set_general_operations, query_params)
      sort_operations(sort_param, operations)
    end

    private
      # query_params is an array where elements are:
        # 1) modality
        # 2) status
        # 3) search
      def self.query_general_operations(operations, query_params)
        modality_param = query_params[0]
        status_param = query_params[1]
        search_param = query_params[2]

        if !modality_param.nil? && status_param.nil? && is_search_empty?(search_param)
          query_by_modality(operations, modality_param)
        elsif !status_param.nil? && modality_param.nil? && is_search_empty?(search_param)
          query_by_status(operations, status_param)
        elsif !is_search_empty?(search_param) && modality_param.nil? && status_param.nil?
          query_by_search(search_param)
        elsif !modality_param.nil? && !status_param.nil? && is_search_empty?(search_param)
          query_by_modality_and_status(operations, modality_param, status_param)
        elsif !modality_param.nil? && !is_search_empty?(search_param) && status_param.nil?
          query_by_modality_and_search(operations, modality_param, search_param)
        elsif !status_param.nil? && !is_search_empty?(search_param) && modality_param.nil?
          query_by_status_and_search(operations, status_param, search_param)
        elsif !status_param.nil? && !is_search_empty?(search_param) && !modality_param.nil?
          query_by_status_and_modality_and_search(operations, modality_param, status_param, search_param)
        else
          operations
        end
      end

  end
end

app/controllers/charts/generals_controller.rb
module Charts	
	class GeneralsController < ApplicationController
		def index
			set_date_range_cookies(params[:day], params[:week], params[:month], params[:year])	
			set_query_params_cookies(params[:modality])
			@modality_content = cookies[:modality]
			@operations = Charts::General.fetch_general_charts(cookies[:date_range_param], @modality_content)
		end

		private
			def set_query_params_cookies(modality)
				if modality.nil?
					cookies.permanent[:modality] = 'ALL'
				else
					cookies.permanent[:modality] = modality
				end
			end
	end
end

app/controllers/generals/tasks_controller.rb
module Generals  
  class TasksController < ApplicationController
    def create
    	task = Generals::Task.new_task(params[:task])
    	if task.save
    		flash[:notice] = 'Task saved'
    		redirect_to operation_path params[:task][:operation_id]
    	else
    		flash[:alert] = 'Could not save task'
    		redirect_to operation_path params[:task][:operation_id]
    	end
    end

    def show
      @id = params[:id]
      @task = Generals::Task.find params[:id]
      @operation_id = @task.operation_id
      @operation = Operation.find(@operation_id)
    end

    def update
      task = Generals::Task.find params[:task][:id]
      task.update(note: params[:task][:note], due_date: params[:task][:due_date], status: params[:task][:status] )
      flash[:notice] = 'Record updated'
      redirect_to operation_path params[:task][:operation_id]
    end
  end
end

app/controllers/records_lists/generals_controller.rb
module RecordsLists	
	class GeneralsController < ApplicationController
	  def index
	  	set_sorting_cookies(params[:oldest], params[:newest], params[:more_progress], params[:less_progress])	
	  	set_query_params_cookies(params[:modality], params[:status], params[:search])
			query_params = [cookies[:modality], cookies[:status], cookies[:search]]
			@operations = RecordsLists::General.fetch_general_operations(cookies[:sort_param], query_params)
	  end
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
	def fcl_exw_steps_cargo_info_id(operation_id)
		FclExwSteps::CargoInfo.find_by(operation_id: operation_id).id
	end

	def fcl_exw_booking_info_step_id(operation_id)
		FclExwSteps::BookingInfo.find_by(operation_id: operation_id).id
	end

	def info_confirmed_step_id(operation_id)
		CommonSteps::InfoConfirmed.find_by(operation_id: operation_id).id
	end

	def info_requested_step_id(operation_id)
		CommonSteps::InfoRequested.find_by(operation_id: operation_id).id
	end

	def quotation_confirmed_step_id(operation_id)
		CommonSteps::QuotationConfirmed.find_by(operation_id: operation_id).id
	end

	def fcl_exw_request_booking_step_id(operation_id)
		FclExwSteps::RequestBooking.find_by(operation_id: operation_id).id
	end

	def fcl_exw_container_loading_step_id(operation_id)
		FclExwSteps::ContainerLoading.find_by(operation_id: operation_id).id
	end

	def fcl_exw_container_delivery_step_id(operation_id)
		FclExwSteps::ContainerDelivery.find_by(operation_id: operation_id).id
	end

	def lcl_steps_cargo_info_id(operation_id)
		LclSteps::CargoInfo.find_by(operation_id: operation_id).id
	end

	def lcl_booking_info_step_id(operation_id)
		LclSteps::BookingInfo.find_by(operation_id: operation_id).id
	end

	def lcl_request_booking_step_id(operation_id)
		LclSteps::RequestBooking.find_by(operation_id: operation_id).id
	end

	def lcl_container_loading_step_id(operation_id)
		LclSteps::ContainerLoading.find_by(operation_id: operation_id).id
	end

	def lcl_container_delivery_step_id(operation_id)
		LclSteps::ContainerDelivery.find_by(operation_id: operation_id).id
	end
end

app/views/generals/tasks/_form.html.erb
<%= form_for :task, url: {controller:'generals/tasks', action: action}, html: { class: 'task-form' }, method: method_var do |f| %>
  <div class="field">
    <%= f.label :note, class: 'label' %>
    <div class="control has-icons-left">
      <%= f.text_area :note, autofocus: true, autocomplete: "note", class: "input note" %>
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <%= f.label :due_date, class: 'label' %>
    <div class="control has-icons-left">
      <%= f.text_field :due_date, autofocus: true, class: 'input due_datetime' %>
      <span class="icon is-small is-left">
        <i class="far fa-calendar-alt"></i>
      </span>
    </div>
  </div>
  <br>
  <% if controller_name == 'tasks' %>
	  <div class="field">
	  	<label class="checkbox">
	  	  <%= f.check_box :status %>
	  	  Mark as completed
	  	</label>
	  </div>
	  <br>
	<% end %>	

  <% if modality == "LCL" %>
    <%= render "generals/tasks/lcl/tasks_loader", step: step, f: f, operation_id: operation_id %>
  <% elsif modality == "FCL - EXW" %>
    <%= render "generals/tasks/fcl_exw/tasks_loader", step: step, f: f, operation_id: operation_id %>
  <% end %>
  <%= f.hidden_field :operation_id, value: operation_id %>
  <%= f.hidden_field :id, value: id %>
  

  <%= f.submit "SAVE", class: 'button is-link' %>
<% end %>

app/views/generals/tasks/_index.html.erb
<%= render 'generals/tasks/tasks_control_bar', operations_by_repre: operations_by_repre, task_subject: task_subject %>


<nav class="panel">
  <% @tasks.each do |task| %>
    <%= link_to generals_task_path(task.id), class: 'panel-block is-active' do  %>
      <span class="panel-icon">
        <i class="fas fa-book" aria-hidden="true"></i>
      </span>
      <p>
        Task for: <b><%= operation(task.operation_id).reference %></b> ---- <span class="blue"> <%= task.note.truncate(120) %> </span> ---- <i class="fas fa-calendar-alt"></i> <%= task.due_date %></b></p>
      </p>
    <% end %>
  <% end %>
</nav>

app/views/generals/tasks/_tasks_control_bar.html.erb
<div class="search-container">
  <div class="columns">

    <%= form_tag users_representative_path, class: 'field is-horizontal column is-12' do %>

      <div class="column">
        <h1 class="title white-font">
          For
        </h1>

        <ul>
          <li>
            <%= button_tag type: "submit", class: "link-button", name: "all" do %>
              <span id='all-tag' class="tag is-rounded <%= is_active_date_range? ('all') %>">   <i class="far fa-calendar-alt tag-icon"></i> All
              </span>
            <% end %>

            <%= button_tag type: "submit", class: "link-button", name: "today" do %>
              <span id='today-tag' class="tag is-rounded inline-tag <%= is_active_date_range? ('today') %>">
                <i class="far fa-calendar-alt tag-icon"></i> Today
              </span>
            <% end %>
          </li>
          <br>
          <li>
            <%= button_tag type: "submit", class: "link-button", name: "this_week" do %>
              <span id='this-week-tag' class="tag is-rounded <%= is_active_date_range? ('this_week') %>">   <i class="far fa-calendar-alt tag-icon"></i> This Week
              </span>
            <% end %>
            <%= button_tag type: "submit", class: "link-button", name: "this_month" do %>
              <span id='more-progress-tag' class="tag is-rounded inline-tag <%= is_active_date_range? ('this_month') %>">
                <i class="far fa-calendar-alt tag-icon"></i> This Month
              </span>
            <% end %>
          </li>
        </ul>
      </div>

      <div class="column">
        <h1 class="title white-font">
          Operation Reference
        </h1>

        <div class="select">
          <%= select_tag :operation_id, options_for_select((operations_by_repre.map { |op| [op.reference, op.id] }).to_a.push('ALL').reverse, cookies[:operation_task_search]), {class: 'full-select', onchange: 'this.form.submit();'} %>
        </div>
      </div>

      <div class="column">
        <h1 class="title white-font">
          Task Type
        </h1>

        <div class="select">
          <%= select_tag :task_subject, options_for_select((task_subject).to_a.push('ALL').reverse, cookies[:operation_task_subject]), {class: 'full-select', onchange: 'this.form.submit();'} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/generals/tasks/_tasks_modal.html.erb
<div class="modal <%= step %>">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">TASKS FOR OPERATION <%= Operation.find(operation_id).reference %></p>
      <button class="delete close-modal <%= step %>" aria-label="close"></button>
    </header>

    <section class="modal-card-body">
      <article class="message is-primary">
        <div class="message-header">
          <p>Create Task For Operation <%= operation_id %></p>
        </div>
        <div class="message-body">
          <%= render 'generals/tasks/form', operation_id: operation_id, action: 'create', id: nil, step: step, method_var: 'post', modality: Operation.find(operation_id).modality %>
        </div>
      </article>
     	<br>
    </section>
  </div>
</div>

app/views/generals/tasks/show.html.erb
<div class="container">
	<br>
	<br>
	<nav class="breadcrumb" aria-label="breadcrumbs">
	  <ul>
	    <li><%= link_to "Operation " + @operation.reference, operation_path(@operation_id)%></li>
	    <li class="is-active"><%= link_to "Task", operation_path(@operation_id) %></li>
	  </ul>
	</nav>

	<nav class="panel is-form-panel card-shadow">
	  <div class="panel-block">
	    <p>
	    	<%= render 'generals/tasks/form', operation_id: @operation_id, action: 'update', method_var: 'put', id: @id, step: 'a', modality: @operation.modality %>
	    </p>
	  </div>
	</nav>
</div>