config/routes.rb
Rails.application.routes.draw do

	resources :operations, only: [:show]
	
	post "/carrier_info", to: "operations#carrier_info"
	put "/change_difficulty", to: "operations#change_difficulty", as: "change_difficulty"

	namespace :documents do
		get "/booking_sheet/:operation_id", to: "booking_sheet#show", as: "booking_sheet"
		get "/slis/:operation_id", to: "sli#show", as: "sli"
		get "/slis/new/:secure_id", to: "sli#new", as: "new_sli"
		post "/slis/create/:secure_id", to: "sli#create", as: "create_sli"
		post "/slis/request_sli/:secure_id", to: "sli#request_sli", as: "request_sli"
		post "/slis/tariff_group", to: "sli#tariff_group", as: "tariff_group"
		get "/invoices/new/:secure_id", to: "invoice#new", as: "new_invoice"
		post "/invoices/create/:secure_id", to: "invoice#create", as: "create_invoice"
		post "/invoices/request_invoice/:secure_id", to: "invoice#request_invoice", as: "request_invoice"
		post "/documents_transfer/:operation_id", to: "documents_transfer#send_mail", as: 'send_documents'
		get 'insurance/new/:secure_id', to: 'insurance#new', as: 'insurance_form'
		get 'insurance/view_pdf/:secure_id', to: 'insurance#view_pdf', as: 'insurance_pdf'
		post 'insurance/create', to: 'insurance#create', as: 'insurance_create'
		post 'insurance/send_info/:operation_id', to: 'insurance#send_info', as: 'insurance_send_info'
		post "/quotation_sell_prices", to: 'quotation_selling#confirm'
		get "/quotation_sell/:id", to: "quotation_selling#show", as: "quotation_sell"
	end

	namespace :fcl_exw_steps do 
		post "/confirm_loading", to: "container_loadings#confirm_loading", as: "confirm_loading"
		post "/confirm_delivery", to: "container_deliveries#confirm_delivery", as: "confirm_delivery"
		post "/request_booking", to: "request_bookings#request_booking"
		resources :cargo_info, only: [:new, :create]
		resources :booking_info, only: [:new, :create]
	end

	namespace :lcl_steps do
		resources :cargo_info, only: [:new, :create]
		post "/request_booking", to: "request_bookings#request_booking"
	end

	namespace :common_steps do
		post "/confirm_info", to: "info_confirmed#confirm_info"
		post "/info", to: "info_requested#request_info"
		post "/quotation/new/:secure_id", to: "quotation_confirmed#update_pricing", as: "new_quotation"
		get  "/quotation/new/:secure_id", to: "quotation_confirmed#new", as: "new_quotation_view"
		post "/confirm_quotation", to: "quotation_confirmed#confirm_quotation"
		post "/pieces", to: "pieces#pieces_for_cargo_info", as: "pieces"
	end

	namespace :charts do
		match "/admin/general_charts", to: "generals#index", as: "general", via: [:get, :post]
		match "/admin/customers_charts", to: "customers#index", as: "customers", via: [:get, :post]
		match "/admin/representatives_charts", to: "representatives#index", as: "representatives", via: [:get, :post]
	end

	namespace :records_lists do
		match "/admin/general_records", to: "generals#index", as: "general", via: [:get, :post]
		match "/admin/customers_records", to: "customers#index", as: "customers", via: [:get, :post]
		match "/admin/representatives_records", to: "representatives#index", as: "representatives", via: [:get, :post]
	end

	namespace :generals do	
		get "/tasks/:id", to: "tasks#show", as: "task"
		post "/tasks", to: "tasks#create", as: "tasks"
		put "/update_tasks", to: "tasks#update", as: "update_tasks"
	end

	devise_for :users, controllers: {
		sessions: 'users/sessions',
		registrations: 'users/registrations'
	}
	namespace :users do	
		match "/representative", to: "representatives#index", as: "representative", via: [:get, :post]
		get '/admin', to: "admins#index", as: "admin"
		get 'relationship/new/:representative_id', to: 'relationships#new', as: 'new_relationship'
		post 'relationship/create', to: 'relationships#create' ,as: 'create_relationship'
		delete 'relationship/destroy', to: 'relationships#destroy' , as: 'destroy_relationship'
		get 'relationship/index_representatives', to: 'relationships#index_representatives', as: 'representatives_list'
		match "/team_leader", to: "teams#index", as: "team", via: [:get, :post]
		get "/team_leader/:id", to: "teams#show", as: "team_member"
		post "/team_leader/change_representative", to: "teams#change_representative", as: "change_representative"
	end
  get '/users/edit/:id', to: 'users#edit', as: 'user'
  patch '/users/edit/:id', to: 'users#update'

  namespace :operations do
  	resources :operations_by_users, only: [:new, :create, :edit, :update]
  end


  devise_scope :user do
	  authenticated :user do
	    root to: 'roots_selector#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end
end

app/models/operation.rb
class Operation < ApplicationRecord
	before_create :randomize_id
	has_many :operations_by_users
	has_one :invoice
	has_one :insurance
	validates :modality, :pol, :pod, :origin_address, :origin_zip_code, :origin_city, :origin_state, :origin_country, presence: true

	private
		def randomize_id
		  begin
		    self.secure_id = SecureRandom.random_number(1_000_000)
		  end while Operation.where(secure_id: self.secure_id).exists?
		end
end

app/models/operations/operations_by_user.rb
module Operations
  class OperationsByUser < ApplicationRecord
    belongs_to :operation
    belongs_to :representative, class_name: 'User', foreign_key: "representative_id"
    belongs_to :agent, class_name: 'User', foreign_key: "agent_id", optional: true
    belongs_to :shipper, class_name: 'User', foreign_key: "shipper_id", optional: true
    belongs_to :consignee, class_name: 'User', foreign_key: "consignee_id", optional: true
    validates :agent_id, :shipper_id, :consignee_id, :operation_id, presence: true

    # fields is an array conteining [ reference, modality, strong_params_for_representatives, current_user, pieces_number ]
    def self.create_for_representatives(fields)
  		operation = create_operation(fields[1], fields[0], fields[4], fields[6], fields[7], fields[8], fields[9], fields[10], fields[11], fields[12], fields[13], fields[14], fields[15], fields[16])
  		@operations_by_user = Operations::OperationsByUser.create(fields[2].merge(operation_id: operation.id, representative_id: fields[3].id))
      errors = (@operations_by_user.errors.full_messages + operation.errors.full_messages).delete_if {|x| x == "Operation must exist" || x == "Operation can't be blank"}
      [@operations_by_user, errors]
    end

    def self.update_for_representatives(fields, operation_id, current_user)
      op = Operation.find operation_id
      update_operation(fields[2], fields[3], fields[4], fields[5], fields[6], fields[7], fields[8], fields[9], fields[10], fields[11], fields[12], op)
      Operations::OperationsByUser.find_by(operation_id: operation_id).update(fields[0].merge(operation_id: op.id, representative_id: current_user.id))
      @operations_by_user = Operations::OperationsByUser.find_by(operation_id: operation_id)
      errors = (@operations_by_user.errors.full_messages + op.errors.full_messages).delete_if {|x| x == "Operation must exist" || x == "Operation can't be blank"}
      [@operations_by_user, errors]
    end

    def self.create_operation_by_representative(params, current_user, strong_params)
      params[:operations_operations_by_user][:agent_id].present? && params[:operations_operations_by_user][:shipper_id].present?
      date_arr = Date.today.to_s.split('-') 
      reference = (current_user.contact_first_name[0..0] + current_user.contact_last_name[0..0] + date_arr[2] + date_arr[1] + date_arr[0][2..4] + last_two_digits).upcase
      fields = [ reference, params[:modality], strong_params, current_user, params[:pieces_number], '', params[:agent_reference], params[:shipper_reference],
      params[:consignee_reference], params[:pol], params[:pod], params[:origin_address], params[:origin_city], params[:origin_state], params[:origin_zip_code], params[:origin_country], params[:destination] ]
      new_operation = create_for_representatives(fields)
    end

    def self.update_operation_by_representative(params, current_user, strong_params, operation_id)
      fields = [ strong_params, current_user, params[:agent_reference], params[:shipper_reference],
      params[:consignee_reference], params[:pol], params[:pod], params[:origin_address], params[:origin_city], params[:origin_state], params[:origin_zip_code], params[:origin_country], params[:destination] ]
      updated_operation = update_for_representatives(fields, operation_id, current_user)
    end

    private
    	def self.create_operation(modality, reference, pieces_number, agent_reference, shipper_reference, consignee_reference, pol, pod, origin_address, origin_city, origin_state, origin_zip_code, origin_country, destination)
    		steps_number = 1
    		if modality == "FCL - EXW"
    			steps_number = 9
          operation = Operation.create(reference: reference, status: 'IN PROGRESS', status_message:'Confirm quotation', 
            modality: modality, steps_number: steps_number, current_step: 0, pieces_number: pieces_number, agent_reference: agent_reference,
            pol: pol, pod: pod, origin_address: origin_address, origin_city: origin_city, origin_state: origin_state, origin_zip_code: origin_zip_code, origin_country: origin_country,
            destination: destination, shipper_reference: shipper_reference, consignee_reference: consignee_reference)
          create_fcl_exw_steps(operation)           
        elsif modality == "LCL"
          steps_number = 9
          #TODO HACER ALGO CON POL Y POD
          operation = Operation.create(reference: reference, status: 'IN PROGRESS', status_message:'Confirm quotation', 
            modality: modality, steps_number: steps_number, current_step: 0, pieces_number: pieces_number, agent_reference: agent_reference,
            pol: pol, pod: pod, origin_address: origin_address, origin_city: origin_city, origin_state: origin_state, origin_zip_code: origin_zip_code, origin_country: origin_country,
            destination: destination, shipper_reference: shipper_reference, consignee_reference: consignee_reference)
          create_lcl_steps(operation)
    			#TODO add other modality cases
    		end
        last_two_digits

        operation
      end

      def self.update_operation(agent_reference, shipper_reference, consignee_reference, pol, pod, origin_address, origin_city, origin_state, origin_zip_code, origin_country, destination, operation)
        operation.update(agent_reference: agent_reference,
          pol: pol, pod: pod, origin_address: origin_address, origin_city: origin_city, origin_state: origin_state, origin_zip_code: origin_zip_code, origin_country: origin_country,
           destination: destination, shipper_reference: shipper_reference, consignee_reference: consignee_reference)
      end

      def self.create_fcl_exw_steps(operation)
        FclExwSteps::ContainerDelivery.create!(operation: operation)
        FclExwSteps::ContainerLoading.create!(operation: operation)
        CommonSteps::InfoConfirmed.create!(operation: operation)
        CommonSteps::QuotationConfirmed.create!(operation: operation)
        CommonSteps::InfoRequested.create!(operation: operation)
        FclExwSteps::RequestBooking.create!(operation: operation)
        Documents::QuotationSelling.create!(operation_id: operation.id)
        Documents::Insurance.create!(operation: operation)
        cargo_info = FclExwSteps::CargoInfo.new(operation: operation)
        cargo_info.save!(validate: false)
        booking_info = FclExwSteps::BookingInfo.new(operation: operation)
        booking_info.save!(validate: false)
      end

      def self.create_lcl_steps(operation)
        #cambiar los fcls
        FclExwSteps::ContainerDelivery.create!(operation: operation)
        FclExwSteps::ContainerLoading.create!(operation: operation)
        CommonSteps::InfoConfirmed.create!(operation: operation)
        CommonSteps::QuotationConfirmed.create!(operation: operation)
        CommonSteps::InfoRequested.create!(operation: operation)
        LclSteps::RequestBooking.create!(operation: operation)
        Documents::QuotationSelling.create!(operation_id: operation.id)
        Documents::Insurance.create!(operation: operation)
        cargo_info = LclSteps::CargoInfo.new(operation: operation)
        cargo_info.save!(validate: false)
        booking_info = FclExwSteps::BookingInfo.new(operation: operation)
        booking_info.save!(validate: false)
      end

      def self.last_two_digits
        if ((Operation.last.nil?) || (Operation.last.created_at < Time.current.beginning_of_day))
          "00"
        else
          ref = (Operation.last.reference.last(2).to_i + 1).to_s
          if ref.length == 1
            ref = '0' + ref
          end
          ref
        end
      end
  end
end

app/controllers/operations/operations_by_users_controller.rb
module Operations
	class OperationsByUsersController < ApplicationController

		before_action :authenticate_user!, :require_new_operation_permission

		def new
		end

		def create
			op = Operations::OperationsByUser.create_operation_by_representative(params, current_user, strong_params_for_representatives)
			if op[1].empty?
				set_notice
				redirect_to operation_path(op[0].operation_id)
			else
				set_alert(op[1], 'create')
			end
		end

		def edit
			@operation = Operation.find(params[:id])
			@op_by_user = Operations::OperationsByUser.find_by(operation_id: @operation.id)
		end

		def update
			op = Operations::OperationsByUser.update_operation_by_representative(params, current_user, strong_params_for_representatives, params[:operation_id])
			if op[1].empty?
				set_notice
				redirect_to operation_path(op[0].operation_id)
			else
				set_alert(op[1], 'update', params[:id])
			end
		end

		private

			def set_notice
				flash[:notice] = "Operation successfuly created."
				cookies.permanent[:redirect_tab] = 'operations_tab'
			end

			def set_alert(error, method, id=nil)
				flash[:alert] = "Please provide the infomartion marked with (*)"
				if method == 'create'
					redirect_to new_operations_operations_by_user_path(error)
				else
					redirect_to edit_operations_operations_by_user_path(id, error)
				end
			end

			def strong_params_for_representatives
				params.require(:operations_operations_by_user).permit(:agent_id, :shipper_id, :consignee_id)
			end
	end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController

	def show
		@operation = Operation.find params[:id]
	end

	def carrier_info
		company_name = User.find(params[:carrier_id]).company_name
		@info = User.where(company_name: company_name)
		render json: @info
	end

	def change_difficulty
		Operation.find(params[:operation_id]).update(difficulty: params[:difficulty])
		redirect_back(fallback_location: authenticated_root_path)
	end
end

app/helpers/operations_helper.rb
module OperationsHelper
	def is_active_sort_method?(sort_param)
		if cookies[:sort_param] == sort_param
			'is-dark'
		else
			''
		end
	end

	def is_active_date_range?(date_range_param)
		if cookies[:date_range_param] == date_range_param
			'is-dark'
		else
			''
		end
	end

	def doc_name(iteration, type=nil)
		if type == 'quotation'
			'Quotation Doc-'+ (iteration+1).to_s 
		elsif type == 'sell-quotation'
			'Sold Support-'+ (iteration+1).to_s 
		else
			'Haz/S Prop/Bonded-'+ (iteration+1).to_s
		end
	end

	def breadcrumb_selector
		redirect = []
		if is_admin?
			redirect = ['Operation Records List', records_lists_general_path]
		elsif is_leader?
			redirect = ['Main Page', authenticated_root_path]
		elsif is_representative?
			redirect = ['Operation Records List', users_representative_path]
		end
	end

	def operation_secure_id(operation)
		operation.secure_id
	end

	def operation(operation_id)
		if operation_id.nil?
			nil
		else
			Operation.find operation_id
		end
	end

	def carriers
		User.carriers
	end

	def fcl_exw_container_loading_tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0',fcl_exw_steps_container_loading_id: FclExwSteps::ContainerLoading.find_by(operation_id: operation))
	end

	def fcl_exw_container_delivery_tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0',fcl_exw_steps_container_delivery_id: FclExwSteps::ContainerDelivery.find_by(operation_id: operation))
	end

	def booking_info_tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0',fcl_exw_steps_booking_info_id: FclExwSteps::BookingInfo.find_by(operation_id: operation))
	end

	def request_booking_tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0',fcl_exw_steps_request_bookings_id: FclExwSteps::RequestBooking.find_by(operation_id: operation))
	end

	def quotation_confirmed_tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0',common_steps_quotation_confirmed_id: CommonSteps::QuotationConfirmed.find_by(operation_id: operation))
	end

	def tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0')
	end

	def cargo_info_tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0', fcl_exw_steps_cargo_info_id: FclExwSteps::CargoInfo.find_by(operation_id: operation))
	end

	def info_confirmed_tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0', common_steps_info_confirmed_id: CommonSteps::InfoConfirmed.find_by(operation_id: operation))
	end

	def info_requested_tasks(operation)
		Generals::Task.where(operation_id: operation, status: '0', common_steps_info_requested_id: CommonSteps::InfoRequested.find_by(operation_id: operation))
	end
end

app/views/operations/_fcl_exw_info_received.html.erb
<div class="timeline-item">
	<div class="timeline-icon  <%= is_fcl_exw_info_confirmed?(operation_id) ? 'step-completed' : '' %>">
		<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="21px" height="20px" viewBox="0 0 21 20" enable-background="new 0 0 21 20" xml:space="preserve">
			<path fill="#FFFFFF" d="M19.998,6.766l-5.759-0.544c-0.362-0.032-0.676-0.264-0.822-0.61l-2.064-4.999
				c-0.329-0.825-1.5-0.825-1.83,0L7.476,5.611c-0.132,0.346-0.462,0.578-0.824,0.61L0.894,6.766C0.035,6.848-0.312,7.921,0.333,8.499
				l4.338,3.811c0.279,0.246,0.395,0.609,0.314,0.975l-1.304,5.345c-0.199,0.842,0.708,1.534,1.468,1.089l4.801-2.822
				c0.313-0.181,0.695-0.181,1.006,0l4.803,2.822c0.759,0.445,1.666-0.23,1.468-1.089l-1.288-5.345
				c-0.081-0.365,0.035-0.729,0.313-0.975l4.34-3.811C21.219,7.921,20.855,6.848,19.998,6.766z"/>
		</svg>
	</div>
	<div class="timeline-content right <%= is_fcl_exw_info_confirmed?(operation_id) ? 'step-completed-no-bg-right' : '' %>">
		<h2 class="<%= is_fcl_exw_info_confirmed?(operation_id) ? 'step-completed' : '' %>">CONFIRM SHIPPER INFORMATION RESPONSE</h2>
		<br>
		<p>
			<center>
				<i class="far fa-check-circle timeline-card-icon <%= is_fcl_exw_info_confirmed?(operation_id) ? 'step-completed-icon' : '' %>""></i>
			</center>

			Please confirm that you have received the cargo information from your cargo agent
			<b><%= agent.company_name %></b> and the shipper <b><%= shipper.company_name %></b>
			<br>
			<br>
			<article class="message is-warning">
			  <div class="message-header">
			  	<p>
			  		<i class="fas fa-exclamation-triangle"></i>  Warning
			  	</p>
			  </div>
			  <div class="message-body">
			    We will send you reminders about this step via <b>email</b> every <b>24 hours</b> until you confirm that you have received the cargo information.
			  </div>
			</article>

			<%= form_tag ("/fcl_exw_confirm_info") do %>
				<%= hidden_field_tag 'shipper_id', shipper.id %>
				<%= hidden_field_tag 'operation_id', operation_id %>
				<%= hidden_field_tag 'agent_id', agent.id %>
				<%= submit_tag 'CONFIRM', class: "button is-link #{is_fcl_exw_info_confirmed?(operation_id) ? 'step-completed' : ''  } " , disabled: is_fcl_exw_info_confirmed?(operation_id)  %>
			<% end %>

	</div>
</div>

app/views/operations/_fcl_exw_initial_timeline_item.html.erb
<div class="timeline-item">
	<div class="timeline-icon step-completed">
		<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="21px" height="20px" viewBox="0 0 21 20" enable-background="new 0 0 21 20" xml:space="preserve">
			<path fill="#FFFFFF" d="M19.998,6.766l-5.759-0.544c-0.362-0.032-0.676-0.264-0.822-0.61l-2.064-4.999
				c-0.329-0.825-1.5-0.825-1.83,0L7.476,5.611c-0.132,0.346-0.462,0.578-0.824,0.61L0.894,6.766C0.035,6.848-0.312,7.921,0.333,8.499
				l4.338,3.811c0.279,0.246,0.395,0.609,0.314,0.975l-1.304,5.345c-0.199,0.842,0.708,1.534,1.468,1.089l4.801-2.822
				c0.313-0.181,0.695-0.181,1.006,0l4.803,2.822c0.759,0.445,1.666-0.23,1.468-1.089l-1.288-5.345
				c-0.081-0.365,0.035-0.729,0.313-0.975l4.34-3.811C21.219,7.921,20.855,6.848,19.998,6.766z"/>
		</svg>
	</div>
	<div class="timeline-content step-completed-no-bg-right right">
		<h2 class="step-completed">NEW EXW - FCL PROCESS</h2>
		<br>
		<p>
			You have initiated a new process for the cargo agent <b><%= agent.company_name %></b> and the shipper <b><%= shipper.company_name %></b>, the shipper will be notified that you will be in charge of their operation in the next step.
		</p>
		<br>
	</div>
</div>

app/views/operations/_relevant_info_modal.html.erb
<div class="modal relevant-info">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">RELEVANT OPERATION INFORMATION</p>
      <button class="delete close-modal relevant-info" aria-label="close"></button>
    </header>

    <section class="modal-card-body">
    	
      <article class="message is-primary">
        <div class="message-header">
          <p>AGENT</p>
        </div>
        <div class="message-body">
          <p>
            <b>Company Name:</b> <%= agent.company_name %>
          </p>
          <br>
          <p>
            <b>Email Address:</b> <%= agent.email %> 
          </p>
          <br>
          <p>
            <b>Phone Number:</b> <%= agent.phone_number %> 
          </p>
          <br>
          <p>
            <b>Contact Name:</b> <%= agent.contact_first_name %> <%= agent.contact_last_name %>
          </p>
        </div>
      </article>
      
      <article class="message is-primary">
        <div class="message-header">
          <p>SHIPPER</p>
        </div>
        <div class="message-body">
          <p>
            <b>Company Name:</b> <%= shipper.company_name %>
          </p>
          <br>
          <p>
            <b>Email Address:</b> <%= shipper.email %> 
          </p>
          <br>
          <p>
            <b>Phone Number:</b> <%= shipper.phone_number %> 
          </p>
          <br>
          <p>
            <b>Contact Name:</b> <%= shipper.contact_first_name %> <%= agent.contact_last_name %>
          </p>
        </div>
      </article>

      <article class="message is-primary">
        <div class="message-header">
          <p>CONSIGNEE</p>
        </div>
        <div class="message-body">
          <p>
            <b>Company Name:</b> <%= consignee.company_name %>
          </p>
          <br>
          <p>
            <b>Email Address:</b> <%= consignee.email %> 
          </p>
          <br>
          <p>
            <b>Phone Number:</b> <%= consignee.phone_number %> 
          </p>
          <br>
          <p>
            <b>Contact Name:</b> <%= consignee.contact_first_name %> <%= consignee.contact_last_name %>
          </p>
        </div>
      </article>
      <br>
    </section>

  </div>
</div>

app/views/operations/_send_documentation_modal.html.erb
<div class="modal send-documents">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">SEND DOCUMENTATION </p>
      <button class="delete close-modal send-documents" aria-label="close"></button>
    </header>

    <section class="modal-card-body">
      <p>
        The following documents will be sent to your documentation operator (<b><%= agent(operation).documental_email %></b>)
      </p>
      <hr>
      <ul>
        <% quotation(operation).files.each do |file| %>
          <li> <b>Quotation: </b><%= link_to file.path.split("/").last, Figaro.env.host + file.url, target: 'blank' %>  </li>
        <% end %>

        <% if quotation_sell(operation).completed %>
          <li>
            <b>Quotation Sold: </b> <a href="<%= Figaro.env.host + '/documents/quotation_sell/' + operation.id.to_s + '.pdf' %>" target="blank"> Quotation Sold Document</a>
          </li>
        <% end %>

        <% quotation_sell(operation).files.each_with_index do |file, i| %>
          <li><b>Quotation Sold Support: </b><%= link_to doc_name(i, 'sell-quotation'), Figaro.env.host + file.url, target: 'blank' %></li>
        <% end %>


        <% if sli(operation).nil? || sli(operation).files.empty? %>
          <li>
            <b>SLI: </b> <a href="<%= Figaro.env.host + '/slis/' + operation.id.to_s + '.pdf' %>" target="blank"> SLI Document</a>
          </li>
        <% else %>
          <li>
            <b>SLI: </b> <a href="<%= Figaro.env.host + sli(operation).files.first.url %>" target="blank"> SLI Document</a> 
          </li>
        <% end %>
        <% unless invoice(operation).nil? %>
          <li>
            <b>Invoice:</b> <a href="<%= Figaro.env.host + invoice(operation).files.first.url %>" target="blank"> Invoice Document </a> 
          </li>
        <% end %>
        <li>
          <b>Booking Sheet:</b> <a href="<%= Figaro.env.host + '/documents/booking_sheet/' + operation.id.to_s + '.pdf' %>" target="blank"> Booking Sheet </a>
        </li>

        <% if @operation.modality == "FCL - EXW" %>
          <% existing_fcl_cargo_info(operation).files.each_with_index do |file, i| %>
            <li><b>Hazmat / Self Propelled / Bonded: </b><%= link_to doc_name(i), Figaro.env.host + file.url, target: 'blank' %></li>
          <% end %>
        <% elsif @operation.modality == "LCL" %>
          <% existing_lcl_cargo_info(operation).files.each_with_index do |file, i| %>
            <li><b>Hazmat / Self Propelled / Bonded: </b><%= link_to doc_name(i), Figaro.env.host + file.url, target: 'blank' %></li>
          <% end %>
        <% end %>
        <li>
          <b>Insurance: </b> <a href="<%= Figaro.env.host + '/documents/insurance/view_pdf/' + operation.secure_id.to_s + '.pdf' %>" target="blank">Insurance Document</a>
        </li>

      </ul>
      <hr>
      <%= form_tag documents_send_documents_path(operation), class: "control full-select quotation" do |f| %>
        <label class="label">Additional Comment:</label>
        <div class="field is-grouped">
          <div class="control has-icons-left full-select">
            <div class="control full-select">
              <%= text_area_tag :additional_comment, '' , class: 'input note full-select'%>
            </div>
            <div class="icon is-small is-left">
              <i class="fas fa-globe"></i>
            </div>
          </div>
        </div>
        <%= submit_tag 'SEND DOCUMENTATION', class: "button is-link" %>
      <% end %>
    </section>

  </div>
</div>

app/views/operations/show.html.erb
<% if is_representative? || is_admin? || is_leader? %>
	<% if @operation.modality == "FCL - EXW" %>
		<%= render "operations/fcl_exw/fcl_frame", operation: @operation %>
	<% elsif @operation.modality == "LCL" %>
		<%= render "operations/lcl/lcl_frame", operation: @operation %>
	<% end %>

<% elsif is_agent? %>
<% end %>